# MCU name
MCU = RP2040
BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040

# Build Options
#   change yes to no to disable
#

ALLOW_WARNINGS = yes 
LTO_ENABLE = no 
WS2812_DRIVER = vendor 
RGBLIGHT_ENABLE = yes 
AUDIO_ENABLE = no 
MOUSEKEY_ENABLE = yes 
EXTRAKEY_ENABLE = yes 
ENCODER_ENABLE = no 
NKRO_ENABLE = yes 
